In [15]:
# get data
import pandas as pd
import numpy as np

path = 'titanic.csv'

df = pd.read_csv(path, index_col=0)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Classification

In [17]:
# label counter
clf_df = df
clf_df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [21]:
#결측치확인 및 제거
clf_df.isnull().sum()
clf_df.fillna(df.mean())

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
#feature selection

In [2]:
clf_df = df
y = clf_df['Survived']
y

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

In [ ]:


X.head()

             Pclass   Age  SibSp  Parch     Fare
PassengerId
1                 3  22.0      1      0   7.2500
2                 1  38.0      1      0  71.2833
3                 3  26.0      0      0   7.9250
4                 1  35.0      1      0  53.1000
5                 3  35.0      0      0   8.0500

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [11]:
lg_model = LogisticRegression(random_state=0)
lg_model.fit(X_train,y_train)
lg_y = lg_model.predict(X_test)

decision_model = DecisionTreeClassifier(random_state=0)
decision_model.fit(X_train, y_train)
decision_y = decision_model.predict(X_test)

randomforest_model = RandomForestClassifier(random_state=0)
randomforest_model.fit(X_train,y_train)
randomforest_y = randomforest_model.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score # 정확도
from sklearn.metrics import confusion_matrix #혼동행렬 ==> k fold

print('---- logistic regression ----')
print(accuracy_score(y_test, lg_y))
print(confusion_matrix(y_test, lg_y))

print('---- decision tree classifier ----')
print(accuracy_score(y_test, decision_y))
print(confusion_matrix(y_test, decision_y))

print('---- random forest classifier ----')
print(accuracy_score(y_test, randomforest_y))
print(confusion_matrix(y_test, randomforest_y))

---- logistic regression ----
0.7374301675977654
[[97 13]
 [34 35]]
---- decision tree classifier ----
0.6424581005586593
[[84 26]
 [38 31]]
---- random forest classifier ----
0.7262569832402235
[[88 22]
 [27 42]]