#202533846 임윤준

중요한것
import pandas as pd (dataframe 사용)
import numpy as np (numpy 사용)

In [21]:
# open csv
import pandas as pd
import numpy as np

path = 'heart.csv'

df = pd.read_csv(path)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
#regression
# age를 통해서 해볼것
# y : age target
# x : age 빼고 나머지
df2 = df.drop('target', axis=1) # target은 뺏음 
y = df2['age']
X = df2.drop('age', axis=1)
X.head()

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,1,3,145,233,1,0,150,0,2.3,0,0,1
1,1,2,130,250,0,1,187,0,3.5,0,0,2
2,0,1,130,204,0,0,172,0,1.4,2,0,2
3,1,1,120,236,0,1,178,0,0.8,2,0,2
4,0,0,120,354,0,1,163,1,0.6,2,0,2

In [25]:
# 훈련을 위한 데이터, 훈련을 위한 정답 데이터
# 테스트 데이터, 이후 나온 값
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=12)

print(X_train.shape, y_train.shape)
print(y_train.shape, y_test.shape)

(242, 12) (242,)
(242,) (61,)

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test))

평균제곱근오차 44.20278214009463

In [27]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 111.81967213114754

In [28]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test))

평균제곱근오차 45.806921311475406

In [ ]:
# classification
# label - target (심장병이다 아니다 확인)
# y 값이 target
# x 값이 나머지
y = df['target']
X = df.drop('target',axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [10]:
# 훈련을 위한 데이터, 훈련을 위한 정답 데이터
# 테스트 데이터, 이후 나온 값
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=12)

print(X_train.shape, y_train.shape)
print(y_train.shape, y_test.shape)

(242, 13) (242,)
(242,) (61,)

In [11]:
# Logisstic, DecisionTree, RandomForestClasification
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [16]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)
lr_y = clf_lr.predict(X_test)

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)
dt_y = clf_dt.predict(X_test)

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
clf_y = rf_clf.predict(X_test)

c:\Users\June\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [18]:
print("\n--- LogisticRegression Classifier ---")
print(accuracy_score(y_test, lr_y))
print(confusion_matrix(y_test, lr_y))

print("\n--- DecisionTreeClassifier Classifier ---")
print(accuracy_score(y_test, dt_y))
print(confusion_matrix(y_test, dt_y))

print("\n--- RandomForestClassifier Classifier ---")
print(accuracy_score(y_test, clf_y))
print(confusion_matrix(y_test, clf_y))

--- LogisticRegression Classifier ---
0.7868852459016393
[[22  9]
 [ 4 26]]

--- DecisionTreeClassifier Classifier ---
0.7213114754098361
[[21 10]
 [ 7 23]]

--- RandomForestClassifier Classifier ---
0.819672131147541
[[23  8]
 [ 3 27]]