#202533846 임윤준

In [2]:
import pandas as pd
import numpy as np

path = 'wine.csv'

# DataFrame으로 읽기
df = pd.read_csv(path, index_col=0) #index_col = 0을 통해서 컬럼갯수 제거
df.head() #빠르게 확긴할 수 있는 명령어

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
Wine,,,,,,,,,,,,,
1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [3]:
# data division (y value)
y = df['Alcohol']    
y.value_counts()
y

Wine
1    14.23
1    13.20
1    13.16
1    14.37
1    13.24
     ...
3    13.71
3    13.40
3    13.27
3    13.17
3    14.13
Name: Alcohol, Length: 178, dtype: float64

In [4]:
# data division (x value)
x = df.drop('Alcohol', axis=1)
x.head()

,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
Wine,,,,,,,,,,,,
1,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
1,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
1,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [5]:
# sklearn model split funcation
from sklearn.model_selection import train_test_split

# train_test_split(arrarys, test_size, random_state, shuffle, stratify)
# arrarys : 분할시킬 데이터
# test_size : 학습 데이터 셋의 비율 (float, int)
# random_state : 데이터 분할시 셔플이 이루어지는데 이를 위한 시드값(int, randomState)
# shuffle : 셔플 여부 설정
# stratify : 지정한 Data의 비율
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.5, random_state=0)

LinearRegression
DecisionTreeRegressor
RandomForestRegressor
KNN

In [7]:
# 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(x_train, y_train)
ly_preds = model.predict(x_test)

print('평균제곱오차', mean_squared_error(ly_preds, y_test))

평균제곱오차 0.32509561005250653

In [10]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(x_train, y_train)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(x_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 0.5048955056179777

In [11]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(x_train, y_train)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(x_test)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test))

평균제곱근오차 0.34479027191011125

In [12]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(n_neighbors=3)
model.fit(x_train,y_train)
ly_preds = model.predict(x_test)

print('평균제곱오차', mean_squared_error(ly_preds, y_test))

평균제곱오차 0.5300808988764046